### DISCUSSION TITLE
How can I tell if connections are being routed to the reader node?

### DISCUSSION THREAD

**Discussion by efenderbosch-atg** [aws/aws-advanced-jdbc-wrapper#986] [Q&A] [answered]
I have all classes that have a Spring JPA repo injected tagged w/ `@Transactional(readOnly = true)` and individual functions tagged w/ `@Transactional(readOnly = write)` if any rows are inserted/updated/deleted.

I can see the driver is introspecting the topology and finding the writer and reader nodes:

```
11:36:36.653 TRACE [nio-8084-exec-2] s.a.j.h.RdsHostListProvider              : Topology: 
   HostSpec[host=qa-reader.xxxx.us-east-1.rds.amazonaws.com, port=3306, READER, AVAILABLE, weight=1905, 2024-05-07 15:36:36.624203]
   HostSpec[host=qa.xxxx.us-east-1.rds.amazonaws.com, port=3306, WRITER, AVAILABLE, weight=5, 2024-05-07 15:36:36.237519]
```

But I also see logs like this, which seem to indicate that it isn't routing to the reader node:

```
11:36:36.624 TRACE [nio-8084-exec-2] s.a.jdbc.states.SessionStateServiceImpl  : Current session state:
autoCommit: true -> true
readOnly: false -> false
catalog: xxxx -> (blank)
schema: (blank) -> (blank)
holdability: (blank) -> (blank)
networkTimeout: 0 -> 5000
transactionIsolation: 4 -> (blank)
typeMap: (blank) -> (blank)
```

I have loggers turned up in `application.yml`:

```yml
spring:
  datasource:
    driver-class-name: software.amazon.jdbc.Driver
    hikari:
      data-source-properties:
        keepSessionStateOnFailover: true
      exception-override-class-name: software.amazon.jdbc.util.HikariCPSQLException

logging.level:
  software.amazon.jdbc: trace
  software.amazon.jdbc.plugin.DefaultConnectionPlugin: debug
  com.zaxxer.hikari: trace
  com.mysql: trace
  org.springframework.data.jpa: debug
```

How can I verify that my read-only transactions are going to the reader node?
