### ISSUE TITLE
Using a custom domain with the Read/Write Splitting Plugin plugin does not work.

### ISSUE THREAD

**Issue by briete** [aws/aws-advanced-jdbc-wrapper#1129]
### Describe the bug

I am trying to connect to Aurora's cluster reader endpoints using the Read/Write Splitting Plugin plugin, but it does not work with custom domains.

I currently have a custom domain set up for Aurora's cluster endpoints in Route53.

If I specify Aurora's cluster writer endpoint as it is in the JDBC URL, I can connect to the reader instance, but if I use the custom domain, I cannot connect to the reader instance. The following logs were output and the hostname was incorrect.

```
Failed to connect to reader host: '{instanceIndentifier}:3306/
```

I looked at the documentation and source code and thought I could use the `clusterInstanceHostPattern` parameter, but it seems that the subdomain depends on the DB instance identifier.

I don't want to change my custom domain for this.

### Expected Behavior

Is there a way to simply specify the writer and reader endpoints for a cluster?

### What plugins are used? What other connection properties were set?

Read/Write Splitting Plugin

### Current Behavior

```
Failed to connect to reader host: '{instanceIndentifier}:3306/
```

### Reproduction Steps

We use Spring Boot:3.1.4. Methods that use reader instances are given `@Transactional(readonly = true)`.

## application.yml

```yaml
spring:
  datasource:
    aws-jdbc-wrapper:
      url: jdbc:aws-wrapper:mysql://customdomain:3306/db
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      wrapper-plugins: readWriteSplitting,auroraConnectionTracker,failover,efm2
      wrapper-dialect: aurora-mysql
      reader-host-selector-strategy: roundRobin
```

## Config

```kotlin
@Bean
fun dataSource(): DataSource {
    val ds = AwsWrapperDataSource()
    val properties = Properties()

    properties["wrapperPlugins"] = awsJdbcWrapperConfig.wrapperPlugins
    properties["wrapperDialect"] = awsJdbcWrapperConfig.wrapperDialect
    properties["readerHostSelectorStrategy"] = awsJdbcWrapperConfig.readerHostSelectorStrategy
    ds.targetDataSourceProperties = properties

    ds.jdbcUrl = awsJdbcWrapperConfig.url
    ds.user = awsJdbcWrapperConfig.username
    ds.password = awsJdbcWrapperConfig.password

    return ds
}
```

### Possible Solution

Allow cluster reader endpoints to be set in the Read/Write Splitting Plugin parameters

### The AWS Advanced JDBC Driver version used

2.3.9

### JDK version used

openjdk 17.0.6 2023-01-17 LTS OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (build 17.0.6+10-LTS, mixed mode, sharing)

### Operating System and version

Linux
