### ISSUE TITLE
Fix REDME

### ISSUE THREAD

**Issue by onacit** [aws/aws-advanced-jdbc-wrapper#1266]
### Describe the issue

In this [README.md](https://github.com/aws/aws-advanced-jdbc-wrapper/tree/main/examples/SpringHibernateExample#readme), the following part seems weird.

> [Optional] You can enable driver logging by adding the following to application.yml:
```yaml
logging:
   level:
   software:
   amazon:
   jdbc: TRACE
```

Shouldn't it be...

```yaml
logging:
  level:
    software.amazon.jdbc: TRACE
```

### Links

https://github.com/aws/aws-advanced-jdbc-wrapper/tree/main/examples/SpringHibernateExample#readme
