### ISSUE TITLE
Unable to see traffic on read replica using read-write-plugin

### ISSUE THREAD

**Issue by amihaescu** [aws/aws-advanced-jdbc-wrapper#1372]
Hello team, 

I am trying to use the aws-advanced-jdbc-wrapper in a `SpringBoot 3.4.4` application that connects to an RDS Aurora Postgres cluster with 2 replicas. I am using `aws-advanced-jdbc-wrapper:2.5.6`

We have a 3 tier architecture - Controller-Service-Repository - with all service classes having the annotation `@Transactional ( readOnly = true)` and only methods that alter the data have `@Transactional` 

Here is some of the configuration 
```
application-prod.yml

  datasource:
    aws-jdbc-wrapper:
      driver-class-name: software.amazon.jdbc.Driver
      url: jdbc:aws-wrapper:postgresql://${env.DATABASE_HOSTNAME}:5432/${env.DATABASE_NAME}?wrapperProfileName=SF_F0&readerInitialConnectionHostSelectorStrategy=roundRobin
      username: ${env.DATABASE_USERNAME}
      password: ${env.DATABASE_PASSWORD}
      type: org.springframework.jdbc.datasource.SimpleDriverDataSource
      wrapper-plugins: readWriteSplitting,failover2,efm2
      wrapper-dialect: aurora-pg
      reader-host-selector-strategy: roundRobin
```
`DATABASE_HOSTNAME` -> points to the writer 

```
@Configuration
class DatabaseConfig {

  @Bean
  fun dataSource(awsJdbcWrapperConfig: AwsJdbcWrapperConfig): DataSource {
    val ds = SimpleDriverDataSource()
    val properties = Properties()

    // wrapper config
    awsJdbcWrapperConfig.wrapperPlugins?.let { properties["wrapperPlugins"] = it }
    awsJdbcWrapperConfig.wrapperDialect?.let { properties["wrapperDialect"] = it }
    awsJdbcWrapperConfig.readerHostSelectorStrategy?.let {
      properties["readerHostSelectorStrategy"] = it
    }
    awsJdbcWrapperConfig.clusterInstanceHostPattern?.let {
      properties["clusterInstanceHostPattern"] = it
    }
    properties["connectTimeout"] = TimeUnit.SECONDS.toMillis(30)

    // https://github.com/aws/aws-advanced-jdbc-wrapper/issues/1138
    // workaround to use internal connection pool
    properties[RdsHostListProvider.CLUSTER_ID.name] = "test"

    ds.setDriverClass(software.amazon.jdbc.Driver::class.java)
    ds.url = awsJdbcWrapperConfig.url
    ds.username = awsJdbcWrapperConfig.username
    ds.password = awsJdbcWrapperConfig.password
    ds.connectionProperties = properties

    // Enable jdbc wrapper internal connection pool
    // https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheReadWriteSplittingPlugin.md#internal-connection-pooling
    ConnectionProviderManager.setConnectionProvider(
      HikariPooledConnectionProvider { _, _ ->
        // https://github.com/brettwooldridge/HikariCP
        val config = HikariConfig()
        config.maximumPoolSize = 10
        config.connectionTimeout = TimeUnit.SECONDS.toMillis(30)

        return@HikariPooledConnectionProvider config
      }
    )
    return ds
  }
}

@ConfigurationProperties(prefix = "spring.datasource.aws-jdbc-wrapper")
data class AwsJdbcWrapperConfig(
  val url: String,
  val username: String,
  val password: String,
  val wrapperPlugins: String?,
  val wrapperDialect: String?,
  val readerHostSelectorStrategy: String?,
  val clusterInstanceHostPattern: String?,
)
```

Any pointer to what I might be doing wrong?

We have some E2E tests that perform both read and write operations, but in the AWS RDS Performance insights I only see traffic on the writer replica.
