### ISSUE TITLE
INSERT INTO Query Being Executed on Reader Instance After Failover in EKS Environment, While Using Two Datasources and Read/Write Splitting (r/w splitting plugin not used)

### ISSUE THREAD

**Issue by bun-paul-kwon** [aws/aws-advanced-jdbc-wrapper#1391]
### Describe the bug

When using the AWS Advanced JDBC Wrapper in an EKS environment, we encounter inconsistent behavior during failover situations with the Aurora cluster. This issue occurs intermittently in the EKS Kubernetes environment. After failover in the Aurora cluster, the application encounters the following error:
```
Caused by: java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement
```

The `application.yaml` configuration is as follows:
```yaml
core:
  master: # write datasource
    datasource:
      driver-class-name: software.amazon.jdbc.Driver
      url: jdbc:aws-wrapper:mysql://bun-test-cluster.cluster-xxxxxxxxxxx.ap-xxxxxxxx-x.rds.amazonaws.com/test_db?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
      username: ####
      password: ####
      hikari:
        minimum-idle: 2
        maximum-pool-size: 4
        max-lifetime: 900000
        exception-override-class-name: software.amazon.jdbc.util.HikariCPSQLException
  slave: # read datasource
    datasource:
      driver-class-name: software.amazon.jdbc.Driver
      url: jdbc:aws-wrapper:mysql://bun-test-cluster.cluster-ro-xxxxxxxxxxx.ap-xxxxxxxx-x.rds.amazonaws.com/test_db?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&logger=Slf4JLogger&useSSL=false
      username: ####
      password: ####
      hikari:
        minimum-idle: 3
        maximum-pool-size: 6
        max-lifetime: 900000
        exception-override-class-name: software.amazon.jdbc.util.HikariCPSQLException
```

We do not want to use the read/write splitting plugin and internal pool provided by AWS Advanced JDBC Wrapper for the following reasons:
- We have implemented the `AbstractRoutingDataSource` interface to select the writer or reader datasource based on the `@Transactional(readOnly=true)` annotation.
- We need to set the number of connections and other HikariCP settings directly in the application.yaml.
- We only want to use HikariCP as the external connection pool (the default Spring Boot connection pool) and only use the `auroraConnectionTracker`, `failover`, and `efm2` plugins.

To summarize, we are using Spring Boot with `@Transactional` annotations for read/write splitting and have implemented `MasterSlaveRoutingDataSource` to dynamically route the datasource based on the transaction's read/write state.

Here is the implementation of `AbstractRoutingDataSource`:
```kotlin
class MasterSlaveRoutingDataSource : AbstractRoutingDataSource() {

    private val log = KotlinLogging.logger {}
    override fun determineCurrentLookupKey(): Any? {
        if (TransactionSynchronizationManager.isCurrentTransactionReadOnly()) {
            log.debug { "### Use Replica DB" }
            return DBType.SLAVE
        }
        log.debug { "### Use Master DB" }
        return DBType.MASTER
    }
}

enum class DBType {
    MASTER, SLAVE
}
```

Here is the Database configuration class:
```kotlin
@Configuration
@EnableTransactionManagement
@EnableJpaRepositories(
    basePackages = ["com.test.api.repository"],
    entityManagerFactoryRef = "coreEntityManager",
    transactionManagerRef = "coreTransactionManager",
    repositoryFactoryBeanClass = CustomJpaRepositoryFactoryBean::class
)
class CoreDatabaseConfig {

    @Bean
    @Primary
    @ConfigurationProperties(prefix = "core.master.datasource")
    fun coreMasterDataSourceProperties(): DataSourceProperties {
        return DataSourceProperties()
    }

    @Bean
    @Primary
    @ConfigurationProperties(prefix = "core.master.datasource.hikari")
    fun coreMasterHikariDataSource(@Qualifier("coreMasterDataSourceProperties") masterProperty: DataSourceProperties): HikariDataSource {
        return masterProperty.initializeDataSourceBuilder().type(HikariDataSource::class.java).build()
    }

    @Bean
    @ConfigurationProperties(prefix = "core.slave.datasource")
    fun coreSlaveDataSourceProperties(): DataSourceProperties {
        return DataSourceProperties()
    }

    @Bean
    @ConfigurationProperties(prefix = "core.slave.datasource.hikari")
    fun coreSlaveHikariDataSource(@Qualifier("coreSlaveDataSourceProperties") slaveProperty: DataSourceProperties): HikariDataSource {
        return slaveProperty.initializeDataSourceBuilder().type(HikariDataSource::class.java).build()
    }

    @Bean
    fun coreRoutingDataSource(
        @Qualifier("coreMasterHikariDataSource") masterDataSource: DataSource,
        @Qualifier("coreSlaveHikariDataSource") slaveDataSource: DataSource
    ): DataSource {
        slaveDataSource.connection.use { } // prepare connection pool
        val dataSourceMap: Map<Any, Any> = hashMapOf(
            DBType.MASTER to masterDataSource,
            DBType.SLAVE to slaveDataSource
        )

        return LazyConnectionDataSourceProxy(MasterSlaveRoutingDataSource().apply {
            this.setDefaultTargetDataSource(masterDataSource)
            this.setTargetDataSources(dataSourceMap)
            this.afterPropertiesSet()
        })
    }

    @Bean
    @Primary
    @ConfigurationProperties(prefix = "core.jpa")
    fun coreJpaProperties(): JpaProperties {
        return JpaProperties()
    }

    @Bean
    @Primary
    fun coreEntityManager(
        builder: EntityManagerFactoryBuilder,
        @Qualifier("coreRoutingDataSource") coreRoutingDataSource: DataSource,
        beanFactory: ConfigurableListableBeanFactory,
        coreDbScheduler: DbScheduler
    ): LocalContainerEntityManagerFactoryBean {
        return builder
            .dataSource(coreRoutingDataSource)
            .packages("com.test.api.entity")
            .properties(
                mapOf(
                    AvailableSettings.BEAN_CONTAINER to SpringBeanContainer(beanFactory),
                    AvailableSettings.IN_CLAUSE_PARAMETER_PADDING to true,
                )
            )
            .scheduler(coreDbScheduler)
            .build()
    }

    @Bean
    @Primary
    fun coreTransactionManager(coreEntityManager: EntityManagerFactory): PlatformTransactionManager {
        return JpaTransactionManager(coreEntityManager)
    }

    @Bean
    @Primary
    fun coreDbScheduler(
        @Value("\${core.master.datasource.hikari.maximum-pool-size}") masterMaxPoolSize: Int,
        @Value("\${core.slave.datasource.hikari.maximum-pool-size}") slaveMaxPoolSize: Int,
        @Value("\${core.maximum-jdbc-thread-pool-size}") poolSize: Int? = null
    ): DbScheduler {
        val maxPoolSize = poolSize ?: (masterMaxPoolSize + slaveMaxPoolSize)
        return DbScheduler.of(maxPoolSize, "coreJdbcScheduler")
    }
}
```

Finally, here is the Service Layer code that triggers the INSERT INTO and SELECT FROM queries:
```kotlin
@Service
class ItemService (
    private val itemRepository: ItemRepository
) {
    /** INSERT INTO **/
    @Transactional(readOnly = false)
    suspend fun createDummyItem(): Item {
        return withContext(Dispatchers.IO) {
            val randomUid = (1..10).random().toLong()
            val randomStr = getRandomString(5)
            val randomPrice = (1..100).random().toLong() * 1000
            itemRepository.save(Item(
                uid = randomUid,
                name = "item-${randomStr}",
                price = randomPrice,
                description = "description-${randomStr}"
            ))
        }
    }

    /** SELECT FROM **/
    @Transactional(readOnly = true)
    suspend fun findItemById(id: Long): Optional<Item> {
        return withContext(Dispatchers.IO) {
            itemRepository.findById(id)
        }
    }
}
```

### Expected Behavior

We expect that after failover in the Aurora cluster, the application should be able to continue executing SQL statements (e.g., `INSERT INTO`) without any issues, both locally and in the EKS environment.

### What plugins are used? What other connection properties were set?

auroraConnectionTracker, failover, efm2

### Current Behavior

- In local computer, after Aurora failover, the application successfully executes the INSERT INTO query.
- In EKS, after Aurora failover, the following error occurs intermittently:
`Caused by: java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement`
- This issue does not occur in local computer, but only intermittently in the EKS environment.

### Reproduction Steps

1. Run the application in the EKS environment.
2. Execute an API call that triggers an INSERT INTO query every second. (e.g.,`ItemService::createDummyItem`, `ItemService:: findItemById `) 
3. Trigger the Aurora cluster failover.
4. Check if the INSERT INTO query continues to function properly after failover.

### Possible Solution

I am having difficulty identifying the cause. 

We are unsure whether the issue is related to the AWS Advanced JDBC Wrapper or the infrastructure (such as AWS VPC, EKS, Istio, or DNS issues). Before investigating infrastructure-level issues, we would like to verify if there is a misconfiguration in the AWS Advanced JDBC Wrapper setup.

### Additional Information/Context

- Kubernetes (AWS EKS)
- Istio
- AWS Aurora MySQL Version: 8.0.mysql_aurora.3.08.2 (1 writer, 3 readers)
- Spring Boot Version: 3.2.0
- Language: Kotlin
- And so on: spring-boot-starter-data-jpa

### The AWS Advanced JDBC Driver version used

2.5.6

### JDK version used

openjdk 17.0.8.1 (Corretto)

### Operating System and version

Amazon Linux release 2023
